#!/bin/bash

# This script removes virtual hosts
# you should put it under /usr/local/bin/
# and run it with sudo rm-vhost

# Set the path to your localhost
www=/var/www
echo "Enter site to be removed"
read sn

read -p "Are you sure you want to remove vhost for $www/$sn? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

# Delete the file with VirtualHost configuration in /etc/apache2/site-available/
rm  /etc/apache2/sites-enabled/$sn.dev.conf
rm /etc/apache2/sites-available/$sn.dev.conf
echo "Removing VirtualHosts"

# Reload Apache2
/etc/init.d/apache2 restart

echo "vhost $sn removed"

