#!/bin/bash

# This script removes directories virtual hosts mysql DB 
# you should put it under /usr/local/bin/
# and run it with sudo rmsite

# Set the path to your localhost
www=/var/www
echo "Enter site to be removed"
read sn

read -p "Are you sure you want to remove $www/$sn? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

# Delete site dir
rm -rf $www/$sn
echo "Removing Directory $www/$sn"

# Delete the database
sn2=`echo $sn|tr '-' '_'`
mysqladmin drop $sn2 --force
echo "Rmoving new mysql database under $sn2"

# Delete the file with VirtualHost configuration in /etc/apache2/site-available/
rm  /etc/apache2/sites-enabled/$sn.dev.conf
rm /etc/apache2/sites-available/$sn.dev.conf
echo "Removing VirtualHosts"

# Reload Apache2
/etc/init.d/apache2 restart

echo "Site $sn.dev has been removed, delete <your_ip> $sn.dev from your host OS' host file"
